Add autorelease execution
camunda-community-hub/community-hub-release-parent pull request #11
Opened 2022-01-12 19:10 UTC by celanthe

This PR adds the `autoReleaseAfterClose` execution to Community Hub Release Parent POM file for Community Action Maven Release.

* Ref: https://github.com/camunda-community-hub/community-action-maven-release/issues/33

* Reason for proposed change: @remcowesterhoud had suggested adding this execution: "We use the community maven release action in https://github.com/camunda-cloud/zeebe-process-test - I just performed a release, and I can see the staging repository in Nexus. However, the workflow is done now, and the release is "finished", but the staging repository is still open. I would expect it to be closed, however, to indicate it's now safe to release. Is there a reason why it's left open? Do we need to do or configure something extra?"

2022-01-13 16:30 UTC, celanthe commented
Oh no! @remcowesterhoud You're 110% correct. 🙈 I will fix this up and make that option a flag as it was intended to be, and I'll grab the right exception for closing automatically also. Thank you so much for the catch and the fix! I very much appreciate it.

2022-01-14 08:09 UTC, remcowesterhoud commented
@celanthe Did you forget to push something? I only see the suggestion I made earlier.

2022-01-14 14:29 UTC, npepinpe commented
Remco's correct, I wouldn't want to release immediately in case we simply want to stage it for now, so it would be good if it was an option. For backwards compatibility's sake I would keep the default to false so there's no sudden surprises when someone updates.

2022-01-14 23:29 UTC, celanthe commented
Hi @npepinpe @remcowesterhoud and @zambrovski! :) Apologies for the confusion, I did forget to push my changes, and then ran into a Git mess. All should be resolved now. I look forward to your review. 

Thank you kindly!

2022-01-18 09:00 UTC, remcowesterhoud requested changes
I'm a bit confused about all the options that were added. I think the only relevant one would be `skipStagingRepositoryClose`. This is set to `false` now, which should be the default so I'm not sure if this will change any behaviour.
However, I don't have much experience with this, so I might be wrong here.

2022-01-19 14:49 UTC, celanthe commented
Hi @remcowesterhoud -- Thanks for the review. 

As far as I can tell by reading the [Sonatype documentation](https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment), the skipStagingRepositoryClose flag should be set to `'false'`, and its default is actually `'true'`. 

"If the configuration parameter `skipStagingRepositoryClose` is set to `true` is passed to the plugin execution, the remote staging repository will not be closed."

As for the other properties, I see what happened there, those were an accidental carryover from my work on a different branch. I'll delete those ASAP and push another commit.

2022-01-20 16:35 UTC, celanthe commented on pom.xml
> +                                    <skipNexusStagingDeployMojo>${camunda-hub-skip-staging}</skipNexusStagingDeployMojo>
Hi @remcowesterhoud -- I removed those properties that were not set in my most recent commit! :)

2022-01-20 16:36 UTC, celanthe commented on pom.xml
> +                                    <nexusUrl>${camunda-hub-nexus-url}</nexusUrl>
Hi @remcowesterhoud! Thank you for the catch--I removed those properties as they weren't set.

2022-01-25 10:00 UTC, remcowesterhoud approved these changes
Hey @celanthe. Sorry for taking so long to get back to you! I guess I've interpreted the docs in a different way. It says:
_**skipStagingRepositoryClose**
Set this to true to turn off the automatic closing of a staging repository after deployment._
Which to me indicated that the default would be false.

However, as I said I don't have too much experience with this so I'll trust your judgement :smile:

2022-01-25 15:53 UTC, merged